regcred:
  registryCredentials:
    - url: ghcr.io
      username: 'mars-office'
      password: '${GH_TOKEN}'

vncPassword: test123

imagePullSecrets:
  - name: regcred

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
  hosts:
    - host: alin.vdi.dev.huna2.com
      paths:
        - path: '/'
          pathType: ImplementationSpecific
  tls:
    - secretName: alin-vdi-ingress-tls
      hosts:
        - alin.vdi.dev.huna2.com